### ISSUE TITLE
Interface for browsing game moves is very slow / non-responsive

### ISSUE THREAD

**Issue by nickolasreynolds** [TCEC-Chess/tcecgui#2]
On both the main competition website and the archives, the interface for browsing through the moves of a game is very slow and non-responsive. It takes 3-5 tenths of a second for the interface to respond and for a move to be updated when you scroll one ply in either direction through the moves of a game. Trying to scroll through multiple moves very quickly results in the interface becoming even more non-responsive, often taking 5-10 seconds to update the display and jumping unpredictably a random number of plies in the direction you were trying to proceed. Additionally, attempting to scroll through a game too quickly sometimes even causes the interface to lock up and become completely non-responsive forever, necessitating a page refresh.

These are not a new issues, these problems have existed since the "beta" website has existed in its earliest form. But I've finally become so frustrated with this portion of the interface being essentially completely unusable that I decided to make an issue for it.

Also please note that this behavior is in stark contrast to literally every other chess website that I've ever used. CCCC, Chessbase, lichess, chess.com, chess24, 2700chess, and more all have snappy interfaces where moves are updated instantaneously, and you can scroll through all the moves of a game as quickly as you want. The interface properly displays all moves and remains functional and snappy the entire time. This is the level of performance that the TCEC interface should match.

**Comment by tcecdev** [comment]
This has been fixed after upgrade to 8core box

**Comment by nickolasreynolds** [comment]
The problem definitely isn't fixed and probably has nothing to do with your server hardware. Without looking at your code, my guess is the problem happens because something like this is happening:

1. The user clicks a button.
2. Whether or not a position has been looked at before, a _synchronous_ request is sent to the server for all the various extra garbage related to each position. (PVs and evaluations for white, black, red kibitzer, blue kibitzer, etc.)
3. The extra garbage finishes downloading.
4. The display is updated with the newly downloaded data.

What you should absolutely 100% definitely be doing instead is this:

1. The user clicks a button.
2. **THE DISPLAY INSTANTANEOUSLY UPDATES WITH INFORMATION THAT IS ALREADY AVAILABLE** (i.e. the moves of the game.)
3. The client checks to see if it has already downloaded the information for the currently displayed position, and if it has, it updates the display and no requests are sent to the server.
4. Otherwise, an **ASYNCHRONOUS** request is sent to server for the various extra garbage.
5. The extra garbage finishes downloading.
6. The extra garbage is stored locally by the client.
7. The display is updated with the newly downloaded data, if that position is still the one being shown.

**Comment by octopoulos** [comment]
Yes, it's one of the problems with the current code.
I'm working on it to make it super fast.

**Comment by Aloril** [comment]
New GUI completely rewritten by octopoulos live now.
